Random-Number: "15,30" # min,máx

TimeToChange: 60 # in minutes

HelmetItem:
  type: SKULL_ITEM
  owner: eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvOTQ3NmU3YTEzMTQxODhjOTczNjRkYTQ4YmNhYzkxYzU4NWNjZTA1OTMwMTI4ZTRmZGM1YTlmNTUxZjkyMmY1In19fQ==
  name: "&4Elmo de Gladiador"
  lore:
    - '&8(/gladiador)'
    - '&fUse esse elmo para conseguir'
    - '&fa confiança do Gladiador!'

TradeItem:
  type: SKULL_ITEM
  owner: eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvNGRhOGE4YzkzODRlMjMyM2UxMzdmYjE0ZWVkOWE3MTczOTgxZmM3NjU5MGM4YmY4OWJlOGI1YmZjNDdkOTJmIn19fQ==
  name: "&4Moeda de Troca"
  lore:
    - '&8(/gladiador)'
    - '&fUse essa moeda para trocar'
    - '&fitens com o Gladiador!'

Sounds:
  trusted:
    sound: LEVEL_UP
    volume: 4
    pitch: 4

  bought:
    sound: NOTE_PLING
    volume: 4
    pitch: 4

  insufficient-coins:
    sound: VILLAGER_NO
    volume: 1
    pitch: 1

  insufficient-helmet:
    sound: VILLAGER_NO
    volume: 1
    pitch: 1

  new-items:
    sound: BAT_TAKEOFF
    volume: 4
    pitch: 1

Messages:
  new-items:
    - ''
    - '&6&lVoltz&f&lMC &8&l➜ &7O &fGladiador &7trouxe novos itens poderosos! Confira digitando &f/gladiador&7.'
    - ''
  gladiator-coin-usage: "&6&lVoltz&f&lMC &8&l➜ &cUso correto: /gladiatorcoin give <jogador> <quantia>."
  gladiator-helmet-usage: "&6&lVoltz&f&lMC &8&l➜ &cUso correto: /gladiatorhelmet give <jogador> <quantia>."

ExtraLore:
  - ''
  - '&fCusto: &7%cost% moedas'

Inventory:
  title: "Gladiador"
  rows: 6
  no-trust:
    1:
      type: BARRIER
      glow: true
      name: "&cVocê não pode comprar itens!"
      lore:
        - '&fO Gladiador ainda não confia'
        - '&fem você! Traga até ele um elmo'
        - '&fde um gladiador que morreu em combate'
        - '&fpara ter acesso aos equipamentos do gladiador!'
      slot: 22
    2:
      type: SKULL_ITEM
      owner: eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvOTQ3NmU3YTEzMTQxODhjOTczNjRkYTQ4YmNhYzkxYzU4NWNjZTA1OTMwMTI4ZTRmZGM1YTlmNTUxZjkyMmY1In19fQ==
      name: "&4Elmo de Gladiador"
      lore:
        - '&fClique para entregar um'
        - '&felmo para o gladiador!'
      action: "GIVE_HELMET"
      slot: 40

  items:
    1:
      type: DIAMOND_HELMET
      attributes: false
      name: "&7Capacete &4[Gladiador]"
      lore:
        - '&7Proteção: &f%random-number%'
        - '&7Inquebrável: &f%random-number%'
      action: "BUY"
      slot: 11
      cost: 2
      enchants:
        - 'PROTECTION_ENVIRONMENTAL,%random-number%'
        - 'DURABILITY,%random-number%'
    2:
      type: DIAMOND_CHESTPLATE
      attributes: false
      name: "&7Peitoral &4[Gladiador]"
      lore:
        - '&7Proteção: &f%random-number%'
        - '&7Inquebrável: &f%random-number%'
      action: "BUY"
      slot: 20
      cost: 2
      enchants:
        - 'PROTECTION_ENVIRONMENTAL,%random-number%'
        - 'DURABILITY,%random-number%'
    3:
      type: DIAMOND_LEGGINGS
      attributes: false
      name: "&7Calça &4[Gladiador]"
      lore:
        - '&7Proteção: &f%random-number%'
        - '&7Inquebrável: &f%random-number%'
      action: "BUY"
      slot: 29
      cost: 2
      enchants:
        - 'PROTECTION_ENVIRONMENTAL,%random-number%'
        - 'DURABILITY,%random-number%'
    4:
      type: DIAMOND_BOOTS
      attributes: false
      name: "&7Botas &4[Gladiador]"
      lore:
        - '&7Proteção: &f%random-number%'
        - '&7Inquebrável: &f%random-number%'
      action: "BUY"
      slot: 38
      cost: 2
      enchants:
        - 'PROTECTION_ENVIRONMENTAL,%random-number%'
        - 'DURABILITY,%random-number%'
    5:
      type: DIAMOND_SWORD
      attributes: false
      name: "&7Espada &4[Gladiador]"
      lore:
        - '&7Afiação: &f%random-number%'
        - '&7Inquebrável: &f%random-number%'
        - '&7Aspecto Flamejante: &f%random-number%'
      action: "BUY"
      slot: 24
      cost: 5
      enchants:
        - 'DAMAGE_ALL,%random-number%'
        - 'DURABILITY,%random-number%'
        - 'FIRE_ASPECT,%random-number%'
    6:
      type: DIAMOND_AXE
      attributes: false
      name: "&7Machado &4[Gladiador]"
      lore:
        - '&7Afiação: &f%random-number%'
        - '&7Eficiência: &f%random-number%'
        - '&7Toque Suave: &f%random-number%'
        - '&7Inquebrável: &f%random-number%'
        - '&7Fortuna: &f%random-number%'
        - '&7Aspecto Flamejante: &f%random-number%'
      action: "BUY"
      slot: 33
      cost: 5
      enchants:
        - 'DAMAGE_ALL,%random-number%'
        - 'DIG_SPEED,%random-number%'
        - 'SILK_TOUCH,%random-number%'
        - 'DURABILITY,%random-number%'
        - 'LOOT_BONUS_BLOCKS,%random-number%'
        - 'FIRE_ASPECT,%random-number%'
    7:
      type: BOW
      attributes: false
      name: "&7Arco &4[Gladiador]"
      lore:
        - '&7Força: &f%random-number%'
        - '&7Chama: &f%random-number%'
        - '&7Inquebrável: &f%random-number%'
        - '&7Infinidade: &f%random-number%'
      action: "BUY"
      slot: 22
      cost: 1
      enchants:
        - 'ARROW_DAMAGE,%random-number%'
        - 'ARROW_FIRE,%random-number%'
        - 'DURABILITY,%random-number%'
        - 'ARROW_INFINITE,%random-number%'
    8:
      type: GOLDEN_APPLE:1
      amount: 64
      attributes: false
      action: "BUY"
      slot: 31
      cost: 1